### ISSUE TITLE
Feature idea: reverse path

### ISSUE THREAD

**Issue by jkjustjoshing** [Yqnn/svg-path-editor#80] opened 2022-06-06 13:13 UTC
I'm trying to combine parts of 2 paths, but one is written in a clockwise order and the other in a counter/anti-clockwise order. I would love to be able to flip the order of the points with a button, which would probably fit well in the "Path operations" section.

https://github.com/krispo/svg-path-utils has an implementation of this that can probably be borrowed or used directly.

**Comment by Yqnn** [comment] 2022-06-06 16:47
Duplicate of #10 

I checked how it's implemented in [krispo/svg-path-utils](https://github.com/krispo/svg-path-utils), it's a relatively naive implementation that just reverts all path components  — doesn't work as expected for relative coordinates, for arcs, for vertical line, horizontal lines or when shorthand curves are used.

**Closed by Yqnn** 2022-06-06 16:47 UTC
